### ISSUE TITLE
Multimeter Card - Colored Slider Meter Not Working

### ISSUE THREAD

**Issue by wagesworld** [snootched/cb-lcars#15]
First, great work and thanks for putting in the effort on these cards.  Trying these out and everything works great except for the Multimeter card colors.

I could not get the multimeter card to change the color of the slider ticks, regardless of entity type or settings.  Tracing back through the code, it appears that the cb-lcars-meter is only adding the gradient colors to the 'inactive' style of the underlying grid button array.

See lines 55-58 of cb-lcars-meter.yaml:
```
                  color: {
                    background: {
                      inactive: variables.__interpolated_rgb(variables.gradient_start_rgb,variables.gradient_end_rgb, i, total_steps)
                    },
```

Shouldn't this be setting the 'default' color and not the 'inactive' one?  Switching it to default does fix it, at least when connected to a media_player entity type and specifying gradient start/end values.

I'll do some more testing, but should I be doing some other config on the front-end to get this to work as is?  Seems like I'd have to only connect to an entity that returned an inactive (off, closed, unlocked) state.

**Comment by snootched** [comment]
Thanks for reporting - this is a known issue (but I forgot to post this on the readme.)
This is fixed in dev branch - and is now being merged for the latest release which I will be posting very shortly.

**Comment by snootched** [comment]
New release is posted - please try this one out to see if it resolves the issue for you.
https://github.com/snootched/cb-lcars/releases/tag/v2025.01.1

**Comment by wagesworld** [comment]
Colored slider bars are indeed working in the new build!  Thanks for the fast response.  However, slight issue with the yaml schema that got updated to support this.  The UI gradient selector is still putting gradient start/end colors under the slider_track:meter node, which doesn't get picked up by the new SVG code since it's looking for it directly under the slider_track node.

Set from the UI:

 ```
 slider_track:
    bar_thickness: 10
    gap: 5
    bar_border_radius: 0
    meter:
      gradient_start_color: "#00fdff"
      gradient_end_color: "#ff2600"
```

You can get around this by manually removing the meter node, and it will correctly show colors in the slider.

```
  slider_track:
    bar_thickness: 10
    gap: 5
    bar_border_radius: 0
    gradient_start_color: "#00fdff"
    gradient_end_color: "#ff2600"
```

Seems you'll need to either update the SVG code to pull this from under the meter node, or update the UI form to put gradients directly under the slider_track node.

**Comment by snootched** [comment]
Indeed! good catch - thanks for the details.
Looks like the form wasn't updated correctly with the new structure.  the `meter` node is now gone and these values will remain under `slider_track` node going forward.

I've made the updates in the form in dev, and will be included in the next release.

Thanks for your report!

**Comment by rchadgray** [comment]
My gradient colors are not working yet.  I rebooted.. i made sure i was on the latest release.

Ideas?


![image](https://github.com/user-attachments/assets/7efe2254-40c9-41c7-aba6-5c3c18c44871)


`  - type: custom:cb-lcars-multimeter-card
    enable_resize_observer: true
    variables:
      _mode: slider
      _vertical: false
      _slider_mode: brightness
      card:
        border:
          left:
            size: 95
          top:
            size: 10
            left_radius: 80
            right_radius: 0
          bottom:
            left_radius: 80
            right_radius: 0
        height: "500"
        width: "500"
        min_height: "60"
      gauge:
        sub_meter:
          show_sub_meter: false
      entity: light.my_bedroom_main_lights
      label: Sun Room
      _show_unit_of_measurement: false
      slider_track:
        meter:
          gradient_start_color: "#00fdff"
          gradient_end_color: "#000000"
      entity_match_slider_start: false
      entity_match_slider_end: false
    tap_action:
      action: toggle
    double_tap_action:
      action: none
    hold_action:
      action: none
    show_label: true
    show_advanced: true
`

**Comment by snootched** [comment]
Yes this is the same issue as above.
The short-term solution above will get you going.  Next release (not posted yet) will have the fix in the card editor to set the correct yaml keys.

Your config:
```yaml
 slider_track: 
   meter:
     gradient_start_color: "#00fdff" 
     gradient_end_color: "#000000" 
```

Working config (move the gradient colour settings up one level and remove meter)
```yaml
 slider_track: 
   gradient_start_color: "#00fdff" 
   gradient_end_color: "#000000" 
```

**Comment by snootched** [comment]
This is fixed in v2025.01.1b - please try it out when you can.

**Comment by rchadgray** [comment]
I can see it on one of my two tablets with the Home Assistant app.  It is an older iPad that it works.  My new iPad i dont see it yet and on PC with Chrome browser it is not showing up yet...

So maybe i still have a caching issue and i need to re-boot clear cache on these devices that are not working.

**Comment by snootched** [comment]
Could be cache yes.  You can try to hard reset the cache, or try incognito mode on your PC.

**Comment by snootched** [comment]
Closing as fixed.  If the problem reoccurs, please raise a new issue and we can look into it further.
